### ISSUE TITLE
error while running the keycloak docker compose up command

### ISSUE THREAD

**Issue by Lijo466** [suchorski/keycloak-docker-compose#2]
The Compose file './docker-compose.yml' is invalid because:
services.keycloak.environment.KC_HOSTNAME_STRICT contains false, which is an invalid type, it should be a string, number, or a null

**Comment by suchorski** [comment]
@Lijo466 According to documentation it is boolean
Documentation: https://www.keycloak.org/server/all-config?q=hostname-strict
